name: Continuous Integration
on:
  push:
    branches: [develop]
jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Clean install dependencies
        run: npm ci
      - name: Run build script
        run: npm run build
      - name: Run test script
        run: npm run test --watchAll=false
